-- v0.53 — on-disk thumbnail dedup catalogue.
--
-- A single ``screenshots`` row carries a ``thumbnail_path`` pointing at a
-- JPEG generated by the capture pipeline. The pipeline is content-blind,
-- so two captures of the same visual frame (idle desktop, modal dialog,
-- locked screen) produce byte-identical files at distinct paths and
-- silently waste disk. :mod:`app.thumb_dedup` walks the table, hashes
-- each thumbnail with SHA-256, and collapses duplicates onto a single
-- canonical file — this table is the registry of "I have already seen
-- this content, here is the canonical path and how many screenshots
-- point at it".
--
-- ``sha256`` is the natural primary key: it's the content's identity,
-- and the dedup pass uses ``INSERT ... ON CONFLICT`` against it to
-- handle "we just hashed something we've already seen" atomically.
--
-- ``path`` stores the canonical on-disk location (the first occurrence
-- of the content) — every duplicate screenshot is rewritten to point
-- here, and the duplicate file is then unlinked.
--
-- ``size_bytes`` is recorded once at first sighting so the dedup pass
-- can report ``bytes_freed`` without re-stat'ing the canonical file for
-- every duplicate it absorbs (the duplicate file is gone by the time
-- we tally).
--
-- ``ref_count`` tracks how many ``screenshots.thumbnail_path`` rows
-- currently resolve to ``path``. It starts at 1 (the first occurrence
-- registers itself) and increments on every subsequent dedup. A future
-- thumbnail eviction pass can use ``ref_count == 1`` rows as
-- "exclusively-owned" candidates and prune the table together with the
-- file when the owning screenshot is deleted.

CREATE TABLE IF NOT EXISTS thumb_content (
    sha256 TEXT PRIMARY KEY,
    path TEXT NOT NULL,
    size_bytes INTEGER NOT NULL,
    ref_count INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_thumb_content_path ON thumb_content(path);
